version: '2'
services:
  mysql:
    image: docker.io/bitnami/mysql:8.0
    ports:
      - '3306:3306'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes

